# Generated by Django 4.2.7 on 2023-11-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/post/', verbose_name='Фотография')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/post/', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Бизнес-идея',
                'verbose_name_plural': 'Бизнес-идеи',
                'ordering': ('-date_time',),
            },
        ),
    ]
