# Generated by Django 4.2.7 on 2023-11-19 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusIdeaCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=2000, verbose_name='Комментарий')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my1.busidea', verbose_name='прокомментированная идея')),
            ],
            options={
                'verbose_name': 'Комментарий под идеей',
                'verbose_name_plural': 'Комментарии под идеями',
                'ordering': ('-date_time', 'idea'),
            },
        ),
    ]
