# Generated by Django 4.2.7 on 2023-11-19 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my1', '0003_busideacom_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busideacom',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my1.busidea', verbose_name='Прокомментированная идея'),
        ),
        migrations.CreateModel(
            name='BusIdeaLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False, verbose_name='Оценка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценил идею')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my1.busidea', verbose_name='Оцененная идея')),
            ],
            options={
                'verbose_name': 'Лайк к идее',
                'verbose_name_plural': 'Лайки к идеям',
                'ordering': ('-idea', 'author', 'is_liked'),
            },
        ),
    ]
