# Generated by Django 4.2.7 on 2023-11-21 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my1', '0005_room_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200, verbose_name='Должность')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('contacts', models.CharField(max_length=300, verbose_name='Контакты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/post/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('-date_time',),
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
