# Generated by Django 4.2.7 on 2023-11-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my1', '0006_vacan_alter_message_content_alter_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Товар')),
                ('amount', models.CharField(default='шт.', max_length=50, verbose_name='Кол-во(штук)')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('product',),
            },
        ),
    ]
