# Generated by Django 4.2.7 on 2023-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my1', '0007_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busideacom',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Комментарий'),
        ),
    ]
